### ISSUE TITLE
2022.3 compatibility

### ISSUE THREAD

**Issue by alechenninger** [YannCebron/m68kplugin#51]
Is it possible to release a version compatible with IntelliJ 2022.3?

It looks like you've updated compatibility on main.

**Comment by YannCebron** [comment]
Yes it's planned "soon". In the meantime you can install snapshot builds from https://github.com/YannCebron/m68kplugin/actions/workflows/build.yml manually via IDE Plugin Manager "Install from Disk"

**Comment by YannCebron** [comment]
Sorry for delay. v0.1.71 is now available https://github.com/YannCebron/m68kplugin/releases/tag/v0.1.71 (should be published on Marketplace within next hours)

**Comment by YannCebron** [comment]
v0.1.71 release was removed due to problems

**Comment by YannCebron** [comment]
v0.1.72 is now available and uploaded to Marketplace https://github.com/YannCebron/m68kplugin/releases/tag/v0.1.72
